config/routes.rb
Rails.application.routes.draw do
  get 'lists/add_item'
  get 'lists/add_item/:id', to: 'lists#add_item', as: 'list_add_item'
  get 'lists/remove_item/:id', to: 'lists#remove_item', as: 'list_remove_items'
  post 'lists/remove_item/:id', to: 'lists#remove_item', as: 'list_remove_item'
  post 'lists/remove/:id/:item_id', to: 'lists#remove', as: 'list_item_removed'
  post 'lists/add_item'
  post 'lists/add'
  resources :lists
  root 'lists#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy, :add_item, :add, :remove_item, :remove]
  before_action :set_item, only: [:remove_item, :remove]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @items = @list.items.all
  end

  def add_item
    @items = @list.items.all
    @item = Item.new
  end

  def add
    @item = Item.new(item_params)
    if @item.save
      @list.items << @item
      redirect_to list_add_item_path(@list)
    end
  end

  def remove_item
    @items = @list.items.all
  end

  def remove
    @list.items.delete(@item)
    redirect_to list_remove_items_path(@list)
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.items.delete_all
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    def set_item
      if params[:item_id] != nil
        @item = Item.find(params[:item_id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title)
    end

    def item_params
      params.require(:item).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoppingList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="col-sm-offset-1 col-md-offset-2 col-sm-10 col-md-8">
    <%= yield %>
  </div>
</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list, :html => { :class => "form-horizontal list" } do |f| %>

  <% if @list.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                lists_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/lists/add_item.html.haml
.page-header
  %h1 Add New Item

%h2= @list.title

%table.table.table-striped
  %thead
    %tr
      %th ID
      %th Item
  %tbody
    - @items.each do |item|
      %tr
        %td= item.id
        %td= item.name

= form_for @item, url: {action: "add", params: {id: @list.id}} do |f|

  .form-group
    = f.label :name, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, class: 'form-control'

  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, class: 'btn btn-primary'
      = link_to "Back", list_path(@list), class: 'btn btn-info'

app/views/lists/edit.html.erb
<%- model_class = List -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lists/index.html.haml
.page-header
  %h1 Shopping Lists
  %table.table.table-striped
    %thead
      %tr
        %th ID
        %th List
        %th
    %tbody
      - @lists.each do |list|
        %tr
          %td= list.id
          %td= list.title
          %td
            = link_to "View", list_path(list), class: 'btn btn-xs btn-info'
            = link_to "Delete", list_path(list), method: :delete, class: 'btn btn-xs btn-danger'
  = link_to "New List", new_list_path, class: 'btn btn-primary'

app/views/lists/new.html.erb
<%- model_class = List -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lists/remove_item.html.haml
.page-header
  %h1 Edit Items

%h2= @list.title

%table.table.table-striped
  %thead
    %tr
      %th ID
      %th Item
      %th
  %tbody
    - @items.each do |item|
      %tr
        %td= item.id
        %td= item.name
        %td= link_to("Delete", list_item_removed_path(@list, item), method: :post, class: 'btn btn-xs btn-danger')

= link_to "Back", list_path(@list), class: 'btn btn-info'

app/views/lists/show.html.haml
.page-header
  %h1 List

%h2= @list.title

%table.table.table-striped
  %thead
    %tr
      %th Item
  %tbody
    - @items.each do |item|
      %tr
        %td= item.name

= link_to "Back", lists_path, class: 'btn btn-info'
= link_to "Edit", edit_list_path(@list), class: 'btn btn-default'
= link_to "Add Items", list_add_item_path(@list), class: 'btn btn-default'
= link_to "Remove Items", list_remove_items_path(@list), class: 'btn btn-default'
= link_to "Delete", list_path(@list), method: :delete, class: 'btn btn-danger'